project_id = "zzjmtipdsccxmmoaetlp"

[functions.stripe-webhook]
verify_jwt = false

[functions.google-client-config]
verify_jwt = false

[functions.get-stripe-config]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.analyze-reviews]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = true

[functions.google-business-accounts]
verify_jwt = true

[functions.google-business-locations]
verify_jwt = true

[functions.google-business-reviews]
verify_jwt = true

[functions.autocomplete-establishments]
verify_jwt = true

[functions.get-place-details]
verify_jwt = true

[functions.find-establishment]
verify_jwt = true

[functions.ai-assistance]
verify_jwt = true

[functions.analyze-establishment]
verify_jwt = true

[functions.activate-creator-subscription]
verify_jwt = true

[functions.update-addon-quantity]
verify_jwt = true

[functions.send-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-email/*.html" ]

[functions.check-email-exists]
enabled = true
verify_jwt = true
import_map = "./functions/check-email-exists/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-email-exists/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-email-exists/*.html" ]
